name: ci

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and test
        uses: docker/build-push-action@v5
        with:
          context: .
          target: test
          load: true
      - name: Build and push
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          # Convert repository name to lowercase
          LOWERCASE_REPO_NAME=$(echo $REPO_NAME | tr '[:upper:]' '[:lower:]')
          /usr/bin/docker buildx build \
            --platform linux/amd64,linux/arm64/v8 \
            --target prod \
            --tag ${{ secrets.DOCKER_USERNAME }}/$LOWERCASE_REPO_NAME:latest \
            --push .
